# Config file for travis continous integration tool

language: c

install:
  - sudo apt-get install texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended 

script: ./testall.sh

notifications:
  email:
    on_success: change
    on_failure: change
