language: c
install: ./install-tex.sh
script: ./make.sh
notifications:
  email:
    on_success: change
    on_failure: change
deploy:
  provider: releases
  api_key:
    secure: 2SlVRh4hC2E+hNjDtqb0CUOilRbv+MU5CD9RN95It6TvZUpgTObYbAVRQdgtdHHiq5P6uy1K1lhk2UvC1B3BSGIXATHlrUnhF+uYj/BcnLTb3/GFcylF06Gp0eInV05R+4i0f8reU+M7FFkfSXNtp8BoVIUAoxqYqsPEemL2VsA=
  file: pdf/*
  on:
    tags: true